const data = [
  {
    courseId: 1,
    title: "하루 30분: 건강한 피트니스 루틴",
    name: "이다빈 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 2,
    title: "유연한 몸: 요가와 스트레칭 클래스",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 3,
    title: "에너지 부스트: 아침 활력 운동",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 4,
    title: "집에서 즐기는 홈트레이닝",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 5,
    title: "강한 코어: 복근 강화 프로그램",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 6,
    title: "마음과 몸의 힐링: 저녁 명상 운동",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 7,
    title: "효과적인 칼로리 소모 운동",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 8,
    title: "파워풀 웨이트 트레이닝",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
];

export default data;
