const data = [
  {
    courseId: 1,
    title: "물개가 되는 법",
    name: "이다빈 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 2,
    title: "물개가 되는 법",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 3,
    title: "물개가 되는 법",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 4,
    title: "물개가 되는 법",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 5,
    title: "물개가 되는 법",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 6,
    title: "물개가 되는 법",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 7,
    title: "물개가 되는 법",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
  {
    courseId: 8,
    title: "물개가 되는 법",
    name: "김예지 강사님",
    sportType: "수영",
    location: "경북 포항시 북구",
    score: 3.5,
    disabilityType: "뇌병변 / 시, 청각 장애 가능",
    price: 30000,
    likeCount: 100,
    isLike: true,
    isGroup: false,
    teacherName: "이다빈 강사님",
    imageURL:
      "https://cdn.pixabay.com/photo/2019/07/01/10/44/water-4309678_1280.jpg",
  },
];

export default data;
